version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:13

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  spotifybox:
    <<: *defaults
    steps:
      - install
      - restore_cache:
          keys:
            - spotify-auth-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - spotify-auth-
      - run: npm start
      - save_cache:
          key: spotify-auth-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - spotify-auth.json

workflows:
  version: 2

  test:
    jobs:
      - spotifybox

  poll:
    triggers:
      - schedule:
          # Run once every 15 mins
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - spotifybox
